/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MemeArtCollectionPortal } from "./MemeArtCollectionPortal";

export { MemeArtCollectionPortal__factory } from "./factories/MemeArtCollectionPortal__factory";
